# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd87e878a9a2d90e20fe86f30985cad2e2e01f545081971233e519f64d85168d15918a78f62218efae1fac855eafee92435b519996bda71979795407aae7aac6

test:
  secret_key_base: e875b7911d88b80d08b3076596e9860b2d1f520d7ea451a9a93f230a5dff0d80455ed5d98375481a294e66ca99019aa0fd3f41b4ecc5c97911f06f5bb2f1379f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
